name: Release to PyPI and GitHub

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --no-interaction --username __token__ --password $POETRY_PYPI_TOKEN_PYPI

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*
          body: |
            ## What's Changed
            
            This release includes improvements and bug fixes. See the full changelog below.
            
            ## Installation
            
            ```bash
            pip install visflow==${{ github.ref_name }}
            ```
            
            ## Quick Start
            
            ```bash
            # Train a model
            visflow train --config config.yml
            
            # Generate GradCAM visualization
            visflow gradcam --ckpt-path model.pth --image-path image.jpg
            ```